### PR TITLE
Feature/us09

### LINKED ISSUE #13: US09 Birth before death of parents
Child should be born before death of mother and before 9 months after death of father

### PR DESCRIPTION
**Pull request by robertschaedler3**
Added tests and merged validation into Validator from US08. 

Closes #13

### CODE REVIEW

**Review by robertschaedler3 — COMMENTED** [review]
We might be able to do similar things to this if the out loops of several validators are the same.

**Review by robertschaedler3 — COMMENTED** [review]
Fix formatting issue in Test.

**Review by Liam-Brew — APPROVED** [review]
nice tests

**Review by allen-best — APPROVED** [review]
Looks good I especially enjoy the use of that helper function in the test.

**Comment by aej11a** [comment]
yup super nice tests

**Review by aej11a — APPROVED** [review]

**Pull request merged**
